### ISSUE TITLE
Consider adding into_pwstr() convenience functions for &str and/or String

### ISSUE THREAD

**Issue by jquesada2016** [microsoft/windows-rs#973]
Currently, converting from UTF-8 to UTF-16, is relatively straightforward, but can become tedious to have to define a helper function for the conversion each time one must use PWSTR in a crate. I believe it would be very useful to implement something like `into_pwstr()` for `&str` and/or `String`. This would also reduce the number of FFI errors on forgetting to add a trailing null byte when encoding, as this isn't usually necessary in Rust.

# Possible Soluction
Currently, my solution is as follows:

```rust
trait IntoPWSTR {
    fn into_pwstr(self) -> (PWSTR, Vec<u16>);
}

impl IntoPWSTR for &str {
    fn into_pwstr(self) -> (PWSTR, Vec<u16>) {
        let mut encoded = self
            .encode_utf16()
            .chain([0u16])
            .collect::<Vec<u16>>();

        (PWSTR(encoded.as_mut_ptr()), encoded)
    }
}
impl IntoPWSTR for String {
    fn into_pwstr(&self) -> (PWSTR, Vec<u16>) {
        let mut encoded = self
            .encode_utf16()
            .chain([0u16])
            .collect::<Vec<u16>>();

        (PWSTR(encoded.as_mut_ptr()), encoded)
    }
}
```

Also note that returning the owned encoded vec is important, so that the contents aren't dropped and the pointer points to freed memory. This is also better than just calling `into_raw_parts()` on the vec, as this will leak memory. Since the owned vec is what is being returned, the caller can decide whether to leak the memory or let the vec drop itself once it goes out of scope.

**Comment by kennykerr** [comment]
Thanks for the suggestion! I'm juggling a few different related problems and solutions but I'll keep this in mind.

**Comment by FreddyD-GH** [comment]
@kennykerr I've seen you mention in other issues that `IntoParam` shouldn't be used by anyone other than the generated bindings.  This issue represents a case where I've (somewhat) regularly used `IntoParam`, just to ensure the logic I'm using to convert the strings doesn't differ from logic the windows crate is using.  Personally, I don't consider this to be an urgent issue, but I just figured I'd give you an FYI if you are trying to break people's habits of using `IntoParam` directly.

**Comment by Zerowalker** [comment]
Is this for cases when it doesn't have `IntoParam`?
```rust
// Fine
RegisterServiceCtrlHandlerExW("MyService", None, std::ptr::null());

// Not fine (is this where the into_pwstr() is intended?)
let table: &[SERVICE_TABLE_ENTRYW] = &[
        SERVICE_TABLE_ENTRYW {
            lpServiceName: "MyService",
            lpServiceProc: None,
        },
        SERVICE_TABLE_ENTRYW {
            ..Default::default()
        },
    ];
```

If this is an example where you are supposed to use it, then i am for it as well.
Unless you can implicitly convert it like with the `fn`, as I don't fully understand how it works so it might just not be possible.

**Comment by tim-weis** [comment]
@Zerowalker If this is strictly about string literals then you can use a crate like [`wchar`](https://crates.io/crates/wchar). It generates UTF-16 strings at compile time so you don't even need to execute any code at run time (as proposed here).

**Comment by Zerowalker** [comment]
@tim-weis i tried that but not sure how i would pass it as a `PWSTR` as it expects a `mut * u16` and `wchar` makes a `&[u16]`.

**Comment by Zerowalker** [comment]
Oh, should i post an issue about that then, so they can correct it?

**Comment by tim-weis** [comment]
@riverar It's not a metadata issue, though. `lpServiceName` is [declared](https://docs.microsoft.com/en-us/windows/win32/api/winsvc/ns-winsvc-service_table_entryw) as having type `LPWSTR` in the SDK header files. The metadata isn't wrong here. It's rather that `LPWSTR` is the *semantically* wrong type (at least for this use).

**Comment by riverar** [comment]
@tim-weis The win32metadata repo is also owned by the SDK folks and can affect changes to the headers, so still a good place to file this. But that'll naturally take a bit longer.

**Comment by kennykerr** [comment]
At this point I think we have enough ways to create strings. If you need literals, you can use the macros introduced by #1891 and if you need to build something at runtime you can always use an `HSTRING`. So, I'm going to close this issue but feel free to keep chatting or create more specific issues for outstanding concerns.

**Comment by jmaasing** [comment]
I had a hard time finding documentation for how to create strings. Maybe the FAQ could have a section about it? 

How to convert strings.

- Convert PWSTR to PCWSTR: `let s: PWSTR...; let r:PCWSTR = PCWSTR(s.0)`
- Convert String to PCWSTR: `let s: String=...; let r:PCWSTR = PCWSTR(HSTRING::from(s).as_ptr())`
- Convert String-literal to PCWSTR:` let r:PCWSTR = w!("example")`

**Comment by MolotovCherry** [comment]
Just want to note for anybody who reads this, be careful of using `PCWSTR(HSTRING::from(s).as_ptr())`, as the `HSTRING` can be dropped before the memory gets read, causing corruption.

To make sure it gets dropped at the end of scope and is able to be accessed properly, make sure you explicitly assign it first.
```rust
let h_title = HSTRING::from(title);
let h_message = HSTRING::from(message);

let title = PCWSTR::from_raw(h_title.as_ptr());
let message = PCWSTR::from_raw(h_message.as_ptr());

unsafe {
    MessageBoxW(None, message, title, icon.into());
}
```

Strictly speaking, it's unsafety in safe code. Probably should be fixed somehow.

**Comment by rgwood** [comment]
> if you need to build something at runtime you can always use an `HSTRING`

@kennykerr I think this could use some documentation somewhere (perhaps a mention in the FAQ). I tend to think of `HSTRING` as "that WinRT string type" and it would never occur to me to use it outside of situations where I'm calling WinRT APIs.

**Comment by fkusche** [comment]
Thank you very much for the heads up regarding the temporaries, @MolotovCherry ! (And sorry for digging up this old thread.)

However, I have a question:
> ```
> // note: don't do this inline or you'll get the same problem with things being dropped as temporaries
> // it must be bound to a variable!
> let foo = "foobar".to_pcwstr();
> SomeCallForPCWSTR(*foo);
> ```
Is that really the case? In my understanding, the temporary will be dropped _after_ `SomeCallForPCWSTR()` returned. So the pointer should be valid during the call. Of course, if the function requires that the pointer stays valid vor a longer time, a temporary is not an appropriate solution here (but that would be the same in C++).

**Comment by fkusche** [comment]
Yes I meant the first variant (`foo("foobar".to_pcwstr().as_pcwstr())`).
And yes, since there is no borrow checker for raw pointers you have to be really careful.
I was just starting to call Windows APIs in Rust and your post noticed me about a problem I was not really thinking about. (That you really have to be careful not to create temporaries at the wrong place.)

I like the updated version of your code.

**Comment by pronebird** [comment]
After reading this thread I still do not understand how to produce `PCWSTR` 🤦
